additionalRepositories:
  - url: https://github.com/NakedFerret/tirs-widgets

vscode:
  extensions:
    - svelte.svelte-vscode

tasks:
  - name: Keystone Admin
    init: yarn install
    command: yarn dev

  - name: Widgets library
    init: |
      cd ../tirs-widgets
      npm install
    command: npm run dev


