additionalRepositories:
  - url: https://github.com/NakedFerret/tirs-widgets

vscode:
  extensions:
    - svelte.svelte-vscode

tasks:
  - name: Keystone Admin
    init: yarn install
    command: |
      cd /workspace/tirs-library
      yarn dev

  - name: Widgets library
    init: |
      cd /workspace/tirs-widgets
      npm install
    command: |
      cd /workspace/tirs-widgets
      npm run dev


